export const SHOP_ROUTE = '/'
export const BASKET_ROUTE = '/cart'
export const DEVICE_ROUTE = '/item/:id'
export const PROFILE_ROUTE = '/profile'
export const PASSWORD_ROUTE = '/passwordChange'
export const HISTORY_ROUTE = PROFILE_ROUTE + '/history'
export const CONTACT_ROUTE = PROFILE_ROUTE + '/contact'
export const DELIVERY_ROUTE = PROFILE_ROUTE + '/delivery'
